services:
  db:
    container_name: db_container_${MODE}
    image: postgres:14.0
    restart: always
    volumes:
      - ~/data/db/${DB_NAME}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    labels:
      - dev.dozzle.name=ab_db_${MODE}

  vkbot:
    container_name: vkbot_container_${MODE}
    build:
      context: .
    restart: always
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ~/data/logs:/AudioBridge/data/logs
    env_file:
      - ~/data/.env.${MODE}
    depends_on:
      - db
    labels:
      - dev.dozzle.name=ab_bot_${MODE}
