# The script for auto-deploy releases

name: Deploy-Release

# The workflow will run when release is pushed into prod branch
on:
  push:
    branches: [ prod ]

# A workflow
jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                path: prod
            - name: Build and run docker compose
              run: cd prod && MODE=prod docker compose --env-file ~/data/.env.prod up --build -d
            - name: Clear unused images
              run: docker image prune -f
