# The script for auto-deploy dev version in from dev branch

name: Deploy-Dev

# The workflow will run when debugging is pushed into dev branch
on:
  push:
    branches:
      - dev
      - 'release/*'

jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              path: dev
            - name: Build and run docker compose
              run: MODE=dev docker compose --env-file ~/data/.env.dev up --build -d
            - name: Clear unused images
              run: docker image prune -f
